version: '3'
services:
  app:
    image: hayd/deno:alpine
    container_name: deno-app
    command: run --allow-net --allow-env app.js
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - production.env
    ports:
      - "8000:8000"
